apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-client
  labels:
    app.kubernetes.io/name: openvpn-client
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: openvpn
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openvpn
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:      
      containers:
        - name: openvpn-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}    
          env:
            - name: OPENVPNSERVER
              value: " {{ .Values.remotehost }}"
          volumeMounts:
            - name: clientconf
              mountPath: /etc/openvpn/tpl
            - name: keys
              mountPath: /etc/openvpn/certs
          command: ['./clientStart.sh']
      volumes:
        - name: clientconf
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: clientconf
        - name: keys
          secret:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            secretName: openvpnkeys
