apiVersion: v1
kind: ConfigMap
metadata:
  name: serverconf
data:
  openvpn.conf: |
      port 1194
      proto udp
      dev tun
      ca /etc/openvpn/certs/ca.crt
      cert /etc/openvpn/certs/server.crt
      key /etc/openvpn/certs/server.key
      dh /etc/openvpn/certs/dh.pem
      server 10.8.0.0 255.255.255.0
      ifconfig-pool-persist ipp.txt
      keepalive 10 120
      tls-auth /etc/openvpn/certs/ta.key 0 
      cipher AES-256-CBC
      persist-key
      persist-tun
      status openvpn-status.log
      verb 3
      explicit-exit-notify 1
  