apiVersion: v1
kind: Service
metadata:
  name: openvpn
  labels:
    app.kubernetes.io/name: openvpn
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 1194
      targetPort: vpn
      protocol: TCP
      name: vpn
  selector:
    app.kubernetes.io/name: openvpn
    app.kubernetes.io/instance: {{ .Release.Name }}
